### ISSUE TITLE
Platform family cannot be `ubuntu`

### ISSUE THREAD

**Issue by MhdSyrwan** [schubergphilis/mod_security#37]
Hi, 
Thanks v.much for creating this cookbook and keeping it up.

I've tried to use this cookbook on `ubuntu 14.04`, but unfortunately there is no package named `libapache-mod-security`, it's named `libapache2-mod-security2`

Tried to fix that by changing the code under the `ubuntu` [case switch](https://github.com/HoneyApps/chef-mod_security/blob/master/recipes/install_base_apache.rb#L121), but the case was unreachable because there is no `platform_family` named `ubuntu` according to ohai as noted [here](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/platform.rb#L178)

**Comment by MhdSyrwan** [comment]
This issue would be solved if pull request #38 was accepted.

**Comment by jro** [comment]
#38 merged, should be fixed. Apologies for delays.

**Comment by MhdSyrwan** [comment]
:+1:
