### ISSUE TITLE
Unable to load mod_security2.so file

### ISSUE THREAD

**Issue by dhanugupta** [schubergphilis/mod_security#6]
Hi
I am getting this error:
Mixlib::ShellOut::ShellCommandFailed: service[httpd](uco-apache::default line 50) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service httpd start ----
STDOUT: Starting httpd: [FAILED]
STDERR: httpd: Syntax error on line 140 of /etc/httpd/conf/httpd.conf: Syntax error on line 1 of /etc/httpd/mods-enabled/mod-security.load: Cannot load /usr/local/modsecurity/lib/mod_security2.so into server: /usr/local/modsecurity/lib/mod_security2.so: cannot open shared object file: No such file or directory

it tries to load .so file from /usr/local ..etc but when i go there there is no file..any ideas?

**Comment by seccubus** [comment]
Which platform are you using?

**Comment by MrSeccubus** [comment]
We found the error will fix shortly.

**Comment by MhdSyrwan** [comment]
Hi,

I'm wondering why it's corrected like this, can you take a look at the latest version of apache cookbook https://github.com/svanzoest-cookbooks/apache2/blob/master/attributes/default.rb#L124

It's `libexec_dir`.

Take a look at this too [change log](https://github.com/svanzoest-cookbooks/apache2/blob/9e1eb9de404fc04f8d8a308761f842c8a0939fe4/CHANGELOG.md), what do you think ?

For me, i was forced to fork the repo and change it to `libexec_dir` to make it work.

**Comment by MrSeccubus** [comment]
O.K. let me put some code around this. It seems there are various versions of the apache cookbook out there in the wild and some use libexecdir and some use libexec_dir
